 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run: pwsh build.ps1
       - run:
          name: test results conversion
          when: always
          command: |
              dotnet tool install -g trx2junit
              trx2junit /**/TestResults/*.trx
       - store_test_results:
            path: /TestResults
       - store_artifacts:
            path: C:\Users\circleci\LocalPackages
